useCSRFProtection: USE_CSRF_PROTECTION
security:
  referrerPolicy: SECURITY_REFERRER_POLICY
  hpkp:
    maxAge: HPKP_MAX_AGE
    sha256s: HPKP_SHA256S
  roles_whitelist: ADMINWEB_ROLES_WHITELIST
  secure_auth_cookie_enabled: SECURE_AUTH_COOKIE_ENABLED
idam:
  base_url: IDAM_BASE_URL
  s2s_url: IDAM_S2S_URL
  service_name: IDAM_SERVICE_NAME
  oauth2:
    token_endpoint: IDAM_OAUTH2_TOKEN_ENDPOINT
    logout_endpoint: IDAM_OAUTH2_LOGOUT_ENDPOINT
    client_id: IDAM_OAUTH2_CLIENT_ID
adminWeb:
  login_url: ADMINWEB_LOGIN_URL
  import_url: ADMINWEB_IMPORT_URL
  jurisdiction_url: ADMINWEB_JURISDICTIONS_URL
  userprofiles_url: ADMINWEB_USER_PROFILE_URL
  saveuserprofiles_url: ADMINWEB_SAVE_USER_PROFILE_URL
  userrole_url: ADMINWEB_USER_ROLE_URL
  alluserroles_url: ADMIN_ALL_USER_ROLES_URL
  createdefinition_url: ADMINWEB_CREATE_DEFINITION_URL
  updatedefinition_url: ADMINWEB_UPDATE_DEFINITION_URL
  deletedefinition_url: ADMINWEB_DELETE_DEFINITION_URL
  definitions_url: ADMINWEB_DEFINITIONS_URL
  whoami_url : ADMINWEB_WHOAMI_URL
  import_audits_url : ADMINWEB_IMPORT_AUDITS_URL
  authorization_url: ADMINWEB_AUTHORIZATION_URL
  elastic_index_url: ADMINWEB_ELASTIC_INDEX_URL
  elastic_case_types_url: ADMINWEB_ELASTIC_CASE_TYPES_URL

secrets:
  ccd:
    microservicekey-ccd-admin: IDAM_ADMIN_WEB_SERVICE_KEY
    ccd-admin-web-oauth2-client-secret: IDAM_OAUTH2_AW_CLIENT_SECRET
    AppInsightsInstrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY
